### ISSUE TITLE
Notifications hidden on log in screen

### ISSUE THREAD

**Issue by Dana-V** [heritamus/Heritamus#12]
When trying to log in and the account or password is incorrect (for example), the notification telling you this will be hidden under the website image. Happens in Chrome and Safari.
<img width="1055" alt="capture d ecran 2018-06-29 a 06 51 39" src="https://user-images.githubusercontent.com/25182177/42073889-75d48afc-7b69-11e8-9d24-e8a190e013bc.png">

**Comment by lviennois** [comment]
Could not reproduce.

Tested in commit 551673b06127c22c13e5e8a694a7f2d08d136714 on Chrome 74 and Firefox 66

**Comment by heritamus** [comment]
Could not reproduce.

Tested in commit 551673b06127c22c13e5e8a694a7f2d08d136714 on Chrome 74 and Firefox 66
