### ISSUE TITLE
Legend contains nodes that aren't present in the graph

### ISSUE THREAD

**Issue by Dana-V** [heritamus/Heritamus#8]
Here, I have only a song, a group and a person. The legend shows "Concept" and "Entity" as well. I haven't deleted any node.
https://gitlab.com/epsilon-alcen/Heritamus/uploads/b7c604f2c61e70e8aa86c72dc7be7836/Capture_d_écran_2018-06-13_à_19.08.48.png

**Comment by heritamus** [comment]
duplicate of gitlab
